### ISSUE TITLE
Image files

### ISSUE THREAD

**Issue by yenchenlin** [eborboihuc/Deep360Pilot-CVPR17#1]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/7057863/28415179-980e0d34-6d1c-11e7-87ae-8d190f7cdd2f.gif)

![sports-360](https://user-images.githubusercontent.com/7057863/28414686-d4264360-6d1a-11e7-9df6-b7352d864048.png)

**Comment by liuxy1005** [comment]
Do you have this dataset? Can you share it with me? Thank you very much
