### ISSUE TITLE
I can' download the code for formatting the input data.

### ISSUE THREAD

**Issue by huoliangyu** [eborboihuc/Deep360Pilot-CVPR17#2]
I'm trying to follow your introduce, but I fail to  download the code, as described in "You can use code from here to convert it to our input format".  Maybe the web page https://yenchenlin/Deep360Pilt-optical-flow is invalidated. Could you please tell me where to download the code? 

Thanks.

**Comment by eborboihuc** [comment]
Thanks for telling us this issue.

There is a typo in our link and it should be [https://github.com/yenchenlin/Deep360Pilot-optical-flow](https://github.com/yenchenlin/Deep360Pilot-optical-flow)
I have updated our README.md. Please check if it is accessible now.

Thanks.

**Comment by liuxy1005** [comment]
Do you have this dataset? Can you share it with me? Thank you very much
