### ISSUE TITLE
can't do train by datasets provided

### ISSUE THREAD

**Issue by Frankdog** [eborboihuc/Deep360Pilot-CVPR17#4]
# can't train model with datasets provided
 when use following command to do training
    `python main.py --mode train --gpu 0 -d bmx -l 10 -b 16 -p classify --opt Adam`    
but got a message 
    `IOError: [Errno 2] No such file or directory: './data/bmx_16boxes/train/label/batch_36.npy'`  
 check the folder of bmx_16boxes  which unzipped from dataset
    `Deep360Pilot-batch-feature.zip`   
this is no label folder in the zip 

also check the `Deep360Pilot_label.zip`
it seems not the batch data, since it is classified in folder named by video URL suffix

**so how can i do the training , looking forward to your answer**

# can you give your implement of object detection code also ?

**Comment by eborboihuc** [comment]
Thanks for point this out! 

I thought it was attached in `Deep360Pilot-batch-feature.zip`. Here is the [Deep360Pilot-batch-label.zip](https://drive.google.com/uc?export=download&id=0B9wE6h4m--wjUXZNQ3cwM245enM) for the batch-based feature. And I also update this download link at edf47a9.

And I update the `Deep360Pilot-batch-feature.zip` as well to match the path arrangement mentioned in [README.md](https://github.com/eborboihuc/Deep360Pilot-CVPR17/blob/tf1.2/README.md) `--model checkpoint/bmx_16boxes_lam10.0/bmx_lam1_classify_best_model`. So if you found it weird to link the model, you can either change it to your path or download the updated model.

**We do not plan to release the object detection code for now.** But I can help explain what detection output is needed in a Wiki post. I will return to you once it is ready.

**Comment by martinivanco** [comment]
> **We do not plan to release the object detection code for now.** But I can help explain what detection output is needed in a Wiki post. I will return to you once it is ready.

Hi!
First of all, thanks for this amazing work! I'm currently working on my thesis on a simillar topic and I would like to try out your solution on my own input videos. Do you still plan to post an explanation on how to get the detection output?

Thanks!
