### ISSUE TITLE
Techical report

### ISSUE THREAD

**Issue by PengWenChen** [eborboihuc/Deep360Pilot-CVPR17#8]
Hello,

You've mentioned "technical report" for the reward function and sensitivity experiments with a link to the paper website.
But I didn't see any file of "technical report".
Could you please also upload this report here?

Many thanks.

**Comment by PengWenChen** [comment]
Oh, I found it. xddd

**Comment by liuxy1005** [comment]
Do you have this dataset? Can you share it with me? Thank you very much
